import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["src/inject-identity.js", "src/inject-stub-*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        Navigator: "readonly",
        NavigatorUAData: "readonly",
        NetworkInformation: "readonly",
        HTMLCanvasElement: "readonly",
        CanvasRenderingContext2D: "readonly",
        OffscreenCanvas: "readonly",
        Blob: "readonly",
        Uint8Array: "readonly",
        atob: "readonly",
        setTimeout: "readonly",
        AudioBuffer: "readonly",
        AnalyserNode: "readonly",
        OfflineAudioContext: "readonly",
        Float32Array: "readonly",
        WebGLRenderingContext: "readonly",
        WebGL2RenderingContext: "readonly",
        Document: "readonly",
        Object: "readonly",
        Array: "readonly",
        WeakMap: "readonly",
        Promise: "readonly",
        Function: "readonly",
        EventTarget: "readonly",
        DOMException: "readonly",
        Infinity: "readonly",
        Credential: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-var": "warn",
      "prefer-const": ["warn", { destructuring: "all" }],
      "eqeqeq": ["warn", "smart"],
    },
  },
  {
    files: ["src/popup.js", "src/background.js", "src/bridge.js", "src/changes.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        location: "readonly",
        URL: "readonly",
        CustomEvent: "readonly",
        chrome: "readonly",
        browser: "readonly",
        console: "readonly",
        confirm: "readonly",
        Blob: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-var": "warn",
      "prefer-const": ["warn", { destructuring: "all" }],
      "eqeqeq": ["warn", "smart"],
    },
  },
  {
    ignores: ["node_modules/", "build-tmp/"],
  },
];
